version: '3'
services:
  ase23:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    ports:
      - 27017:27017
